[2024-03-11T18:06:55.564+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-11T18:06:55.573+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-11T18:06:55.573+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-11T18:06:55.585+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): Hello_with_bash> on 2023-01-01 00:00:00+00:00
[2024-03-11T18:06:55.589+0000] {standard_task_runner.py:60} INFO - Started process 2610 to run task
[2024-03-11T18:06:55.592+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'BashOperator', 'Hello_with_bash', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/1PrimerDag.py', '--cfg-path', '/tmp/tmp_e6j1l3z']
[2024-03-11T18:06:55.593+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask Hello_with_bash
[2024-03-11T18:06:55.636+0000] {task_command.py:423} INFO - Running <TaskInstance: BashOperator.Hello_with_bash scheduled__2023-01-01T00:00:00+00:00 [running]> on host 482398f6ce07
[2024-03-11T18:06:55.700+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BashOperator' AIRFLOW_CTX_TASK_ID='Hello_with_bash' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2024-03-11T18:06:55.702+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-11T18:06:55.702+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo'Hola este es mi primer BashOperator'"]
[2024-03-11T18:06:55.711+0000] {subprocess.py:86} INFO - Output:
[2024-03-11T18:06:55.712+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoHola este es mi primer BashOperator: command not found
[2024-03-11T18:06:55.712+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-11T18:06:55.720+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-11T18:06:55.723+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=BashOperator, task_id=Hello_with_bash, execution_date=20230101T000000, start_date=20240311T180655, end_date=20240311T180655
[2024-03-11T18:06:55.734+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task Hello_with_bash (Bash command failed. The command returned a non-zero exit code 127.; 2610)
[2024-03-11T18:06:55.765+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-11T18:06:55.817+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
