[2024-03-11T18:05:36.019+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2022-08-24T00:00:00+00:00 [queued]>
[2024-03-11T18:05:36.040+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2022-08-24T00:00:00+00:00 [queued]>
[2024-03-11T18:05:36.040+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-11T18:05:36.072+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): Hello_with_bash> on 2022-08-24 00:00:00+00:00
[2024-03-11T18:05:36.085+0000] {standard_task_runner.py:60} INFO - Started process 2197 to run task
[2024-03-11T18:05:36.093+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'BashOperator', 'Hello_with_bash', 'scheduled__2022-08-24T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/1PrimerDag.py', '--cfg-path', '/tmp/tmptxi61gm4']
[2024-03-11T18:05:36.095+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask Hello_with_bash
[2024-03-11T18:05:36.185+0000] {task_command.py:423} INFO - Running <TaskInstance: BashOperator.Hello_with_bash scheduled__2022-08-24T00:00:00+00:00 [running]> on host 482398f6ce07
[2024-03-11T18:05:36.351+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BashOperator' AIRFLOW_CTX_TASK_ID='Hello_with_bash' AIRFLOW_CTX_EXECUTION_DATE='2022-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-24T00:00:00+00:00'
[2024-03-11T18:05:36.357+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-11T18:05:36.360+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo'Hola este es mi primer BashOperator'"]
[2024-03-11T18:05:36.388+0000] {subprocess.py:86} INFO - Output:
[2024-03-11T18:05:36.390+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoHola este es mi primer BashOperator: command not found
[2024-03-11T18:05:36.391+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-11T18:05:36.409+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-11T18:05:36.415+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=BashOperator, task_id=Hello_with_bash, execution_date=20220824T000000, start_date=20240311T180536, end_date=20240311T180536
[2024-03-11T18:05:36.456+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task Hello_with_bash (Bash command failed. The command returned a non-zero exit code 127.; 2197)
[2024-03-11T18:05:36.485+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-11T18:05:36.688+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
