[2024-03-11T18:08:12.028+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2024-03-11T18:08:12.041+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2024-03-11T18:08:12.042+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-11T18:08:12.057+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): Hello_with_bash> on 2023-05-22 00:00:00+00:00
[2024-03-11T18:08:12.063+0000] {standard_task_runner.py:60} INFO - Started process 3050 to run task
[2024-03-11T18:08:12.068+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'BashOperator', 'Hello_with_bash', 'scheduled__2023-05-22T00:00:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/1PrimerDag.py', '--cfg-path', '/tmp/tmp009q04bm']
[2024-03-11T18:08:12.069+0000] {standard_task_runner.py:88} INFO - Job 331: Subtask Hello_with_bash
[2024-03-11T18:08:12.128+0000] {task_command.py:423} INFO - Running <TaskInstance: BashOperator.Hello_with_bash scheduled__2023-05-22T00:00:00+00:00 [running]> on host 482398f6ce07
[2024-03-11T18:08:12.218+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BashOperator' AIRFLOW_CTX_TASK_ID='Hello_with_bash' AIRFLOW_CTX_EXECUTION_DATE='2023-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-22T00:00:00+00:00'
[2024-03-11T18:08:12.220+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-11T18:08:12.221+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo'Hola este es mi primer BashOperator'"]
[2024-03-11T18:08:12.234+0000] {subprocess.py:86} INFO - Output:
[2024-03-11T18:08:12.235+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoHola este es mi primer BashOperator: command not found
[2024-03-11T18:08:12.236+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-11T18:08:12.246+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-11T18:08:12.250+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=BashOperator, task_id=Hello_with_bash, execution_date=20230522T000000, start_date=20240311T180812, end_date=20240311T180812
[2024-03-11T18:08:12.264+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 331 for task Hello_with_bash (Bash command failed. The command returned a non-zero exit code 127.; 3050)
[2024-03-11T18:08:12.280+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-11T18:08:12.298+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
