[2024-03-11T18:03:08.986+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash manual__2024-03-11T18:03:05.564662+00:00 [queued]>
[2024-03-11T18:03:08.999+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash manual__2024-03-11T18:03:05.564662+00:00 [queued]>
[2024-03-11T18:03:08.999+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-11T18:03:09.031+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): Hello_with_bash> on 2024-03-11 18:03:05.564662+00:00
[2024-03-11T18:03:09.040+0000] {standard_task_runner.py:60} INFO - Started process 2026 to run task
[2024-03-11T18:03:09.047+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'BashOperator', 'Hello_with_bash', 'manual__2024-03-11T18:03:05.564662+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/1PrimerDag.py', '--cfg-path', '/tmp/tmphis9e331']
[2024-03-11T18:03:09.049+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask Hello_with_bash
[2024-03-11T18:03:09.126+0000] {task_command.py:423} INFO - Running <TaskInstance: BashOperator.Hello_with_bash manual__2024-03-11T18:03:05.564662+00:00 [running]> on host 482398f6ce07
[2024-03-11T18:03:09.237+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BashOperator' AIRFLOW_CTX_TASK_ID='Hello_with_bash' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T18:03:05.564662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-11T18:03:05.564662+00:00'
[2024-03-11T18:03:09.241+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-11T18:03:09.242+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo'Hola este es mi primer BashOperator'"]
[2024-03-11T18:03:09.254+0000] {subprocess.py:86} INFO - Output:
[2024-03-11T18:03:09.261+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoHola este es mi primer BashOperator: command not found
[2024-03-11T18:03:09.262+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-11T18:03:09.272+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-11T18:03:09.277+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=BashOperator, task_id=Hello_with_bash, execution_date=20240311T180305, start_date=20240311T180308, end_date=20240311T180309
[2024-03-11T18:03:09.300+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task Hello_with_bash (Bash command failed. The command returned a non-zero exit code 127.; 2026)
[2024-03-11T18:03:09.343+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-11T18:03:09.376+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
