[2024-03-11T18:05:51.400+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-11T18:05:51.424+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-11T18:05:51.425+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-11T18:05:51.476+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): Hello_with_bash> on 2022-09-19 00:00:00+00:00
[2024-03-11T18:05:51.484+0000] {standard_task_runner.py:60} INFO - Started process 2280 to run task
[2024-03-11T18:05:51.489+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'BashOperator', 'Hello_with_bash', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/1PrimerDag.py', '--cfg-path', '/tmp/tmpq6wzgv_8']
[2024-03-11T18:05:51.491+0000] {standard_task_runner.py:88} INFO - Job 85: Subtask Hello_with_bash
[2024-03-11T18:05:51.644+0000] {task_command.py:423} INFO - Running <TaskInstance: BashOperator.Hello_with_bash scheduled__2022-09-19T00:00:00+00:00 [running]> on host 482398f6ce07
[2024-03-11T18:05:52.005+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BashOperator' AIRFLOW_CTX_TASK_ID='Hello_with_bash' AIRFLOW_CTX_EXECUTION_DATE='2022-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-09-19T00:00:00+00:00'
[2024-03-11T18:05:52.007+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-11T18:05:52.010+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo'Hola este es mi primer BashOperator'"]
[2024-03-11T18:05:52.037+0000] {subprocess.py:86} INFO - Output:
[2024-03-11T18:05:52.038+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoHola este es mi primer BashOperator: command not found
[2024-03-11T18:05:52.040+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-11T18:05:52.067+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-11T18:05:52.074+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=BashOperator, task_id=Hello_with_bash, execution_date=20220919T000000, start_date=20240311T180551, end_date=20240311T180552
[2024-03-11T18:05:52.117+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 85 for task Hello_with_bash (Bash command failed. The command returned a non-zero exit code 127.; 2280)
[2024-03-11T18:05:52.160+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-11T18:05:52.211+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
