[2024-03-11T18:06:33.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2022-11-18T00:00:00+00:00 [queued]>
[2024-03-11T18:06:33.520+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BashOperator.Hello_with_bash scheduled__2022-11-18T00:00:00+00:00 [queued]>
[2024-03-11T18:06:33.521+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-11T18:06:33.539+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): Hello_with_bash> on 2022-11-18 00:00:00+00:00
[2024-03-11T18:06:33.544+0000] {standard_task_runner.py:60} INFO - Started process 2469 to run task
[2024-03-11T18:06:33.547+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'BashOperator', 'Hello_with_bash', 'scheduled__2022-11-18T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/1PrimerDag.py', '--cfg-path', '/tmp/tmprz6ndsoc']
[2024-03-11T18:06:33.548+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask Hello_with_bash
[2024-03-11T18:06:33.608+0000] {task_command.py:423} INFO - Running <TaskInstance: BashOperator.Hello_with_bash scheduled__2022-11-18T00:00:00+00:00 [running]> on host 482398f6ce07
[2024-03-11T18:06:33.733+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BashOperator' AIRFLOW_CTX_TASK_ID='Hello_with_bash' AIRFLOW_CTX_EXECUTION_DATE='2022-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-18T00:00:00+00:00'
[2024-03-11T18:06:33.735+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-11T18:06:33.737+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo'Hola este es mi primer BashOperator'"]
[2024-03-11T18:06:33.759+0000] {subprocess.py:86} INFO - Output:
[2024-03-11T18:06:33.766+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoHola este es mi primer BashOperator: command not found
[2024-03-11T18:06:33.769+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-11T18:06:33.786+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-11T18:06:33.791+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=BashOperator, task_id=Hello_with_bash, execution_date=20221118T000000, start_date=20240311T180633, end_date=20240311T180633
[2024-03-11T18:06:33.811+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task Hello_with_bash (Bash command failed. The command returned a non-zero exit code 127.; 2469)
[2024-03-11T18:06:33.841+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-11T18:06:33.871+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
